vorto:
  repository:
    base:
      path: http://localhost:8080/infomodelrepository

http:
  proxyHost:
  proxyPort: 8080

server:
  port: 9080
  contextPath: /editor

github:
  client:
    clientId:  ${github_clientid}
    clientSecret: ${github_secret}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope:
      - user:email
  resource:
    userInfoUri: https://api.github.com/user

repo.configFile: vorto-repository-config-file.json
