# docker-compose-build.yml
version: '2'

services:
  vorto-repo-host:
    build:
      context: ./repo
    image: vorto/infomodelrepository

  vorto-markdown-generator-host:
    build:
      context: ./generators/org.eclipse.vorto.codegen.service.markdown
    image: vorto/markdown-generator

  vorto-bosch-generator-host:
    build:
      context: ./generators/org.eclipse.vorto.codegen.service.bosch
    image: vorto/bosch-generator

  vorto-ios-generator-host:
    build:
      context: ./generators/org.eclipse.vorto.codegen.service.ios
    image: vorto/ios-generator

  vorto-javabean-generator-host:
    build:
      context: ./generators/org.eclipse.vorto.codegen.service.javabean
    image: vorto/javabean-generator

  vorto-mqtt-generator-host:
    build:
      context: ./generators/org.eclipse.vorto.codegen.service.mqtt
    image: vorto/mqtt-generator

  vorto-thingworx-generator-host:
    build:
      context: ./generators/org.eclipse.vorto.codegen.service.thingworx
    image: vorto/thingworx-generator

  vorto-webdevice-generator-host:
    build:
      context: ./generators/org.eclipse.vorto.codegen.service.webdevice
    image: vorto/webdevice-generator

  vorto-latex-generator-host:
    build:
      context: ./generators/org.eclipse.vorto.codegen.service.latex
    image: vorto/latex-generator

  vorto-coap-generator-host:
    build:
      context: ./generators/org.eclipse.vorto.codegen.service.coap
    image: vorto/coap-generator

  vorto-jsonschema-generator-host:
    build:
      context: ./generators/org.eclipse.vorto.codegen.service.jsonschema
    image: vorto/jsonschema-generator
