version: '3'
services:
  repository:
    build: eclipsevorto/vorto-repo
    ports:
      - "8080:8080"
    volumes:
      - "./repository-web/docker:/code/config"
    environment:
    - USE_PROXY=0
    networks:
      - backend
  generators:
    depends_on: ["repository"]
    build: eclipsevorto/vorto-generators
    volumes:
      - "./repository-web/docker:/gen/config"
    networks:
      - backend
  generators-example:
    depends_on: ["repository"]
    build: eclipsevorto/vorto-generators-3d-party
    volumes:
      - "./repository-web/docker:/gen/config"
    networks:
      - backend
networks:
  backend:
    driver: bridge
