server:
  port: 8443
  contextPath: /infomodelrepository
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: Vorto123!
    keyStoreType: jks
    keyAlias: vorto-selfsigned

github:
  oauth2:
    enabled: true
    client:
      clientId: ${github_clientid}
      clientSecret: ${github_secret}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      scope:
         - user
    resource:
      userInfoUri: https://api.github.com/user
    
eidp:
  oauth2:
    enabled: false
    client:
      clientId: 
      clientSecret: 
      accessTokenUri: https://accounts.bosch.com/adfs/oauth2/token
      userAuthorizationUri: https://accounts.bosch.com/adfs/oauth2/authorize
      clientAuthenticationScheme: form
      resource: 
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://accounts.bosch.com/adfs/userinfo
      preferTokenInfo: true

mail:
  smtp:
    host: localhost
    port: 25
  from: vorto-dev@eclipse.org
