#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

server:
  port: 8080
  contextPath: /infomodelrepository
  use-forward-headers: true
  admin: aedelmann, erlemantos, kolotu, t-gauss, mena-bosch
  config:
    authenticatedSearchMode: false
    generatorUser: generator
    generatorPassword: 123
    cors:
      # expresses allowed origins as patterns (e.g. dot escaped)
      # CorsConfiguration bean in SecurityConfiguration overloads origin verification mechanism to
      # support regex if standard ignore-case equality checks fail
      allowedOrigins: http[s]*://www\.eclipse\.org(:\d+)*, http[s]*://vorto\.eclipse\.org*(:\d+)*, http[s]*://localhost(:\d+)*, http[s]*://(.+\.)*?bosch-iot-suite\.com(:\d+)*, http[s]*://(.+\.)*?bosch-iot-cloud\.com(:\d+)*, http[s]*://(.+\.)*?bosch-si.com(:\d+)*, http[s]*://(.+\.)*?bosch.io(:\d+)*

spring:
  jackson.serialization.write-dates-as-timestamps: false
  http.multipart.max-file-size: 20MB
  http.multipart.max-request-size: 15MB

repo:
  config:
    maxModelImageSize: 32000
    maxModelSize: 2000000
    maxBackupSize: 20000000
    predefinedTenants:
      -
        tenantId: standardization
        defaultNamespace: org.eclipse.vorto
        namespaces:
        authenticationProvider: GITHUB
        authorizationProvider: DB
  attachment.allowed:
    extension: ext, pdf, doc, zip, jpg, png, svg, html, json, yml, yaml
    fileSize: 5

eclipse:
  oauth2:
    enabled: true
    client:
      clientId: ${eclipse_clientid}
      clientSecret: ${eclipse_clientSecret}
      accessTokenUri: https://accounts.eclipse.org/oauth2/token
      userAuthorizationUri: https://accounts.eclipse.org/oauth2/authorize
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://accounts.eclipse.org/oauth2/UserInfo

github:
  oauth2:
    enabled: true
    client:
      clientId: ${github_clientid}
      clientSecret: ${github_clientSecret}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      scope:
         - user:email
    resource:
      userInfoUri: https://api.github.com/user

eidp:
  oauth2:
    enabled: false
    client:
      clientId: ${eidp_clientid}
      clientSecret: ${eidp_clientSecret}
      accessTokenUri: https://identity.bosch.com/connect/token
      userAuthorizationUri: https://identity.bosch.com/connect/authorize
      clientAuthenticationScheme: form
      resource: https://vorto.eclipse.org
      scope:
        - openid
        - email
        - profile
    resource:
      logoutEndpointUrl: https://identity.bosch.com/connect/endsession
      userInfoUri: https://identity.bosch.com/connect/userinfo
      logoutRedirectUrl: 
      preferTokenInfo: true

oauth2:
  verification:
    legacy:
      issuer: https://access.bosch-iot-suite.com/auth/realms/iot-suite
      publicKeyUri: https://access.bosch-iot-suite.com/auth/realms/iot-suite/protocol/openid-connect/certs
    hydra:
      issuer: https://access.bosch-iot-suite.com/v2/
      publicKeyUri: https://access.bosch-iot-suite.com/v2/.well-known/jwks.json
      
mail:
  smtp:
    host: localhost
    port: 25
    auth: false
  from: vorto-dev@eclipse.org
  login:
    username:
    password:

config:
  restrictTenant: 1
