repo:
  configFile: vorto-repository-config-file.json

# Plugin Configuration for generators running on AWS
plugins : "W3sia2V5IiA6ICJib3NjaGlvdHN1aXRlIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQifSwKCQkJeyJrZXkiIDogImVjbGlwc2VkaXR0byIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cHM6Ly9peW5vM216eDFoLmV4ZWN1dGUtYXBpLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL0RldmVsb3BtZW50In0sCgkJICAgIHsia2V5IiA6ICJlY2xpcHNlaG9ubyIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cHM6Ly9peW5vM216eDFoLmV4ZWN1dGUtYXBpLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL0RldmVsb3BtZW50In0sCgkJICAgIHsia2V5IiA6ICJwcm90b2J1ZiIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cHM6Ly9peW5vM216eDFoLmV4ZWN1dGUtYXBpLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL0RldmVsb3BtZW50IiwidGFnIiA6ICJkZW1vIn0sCgkJICAgIHsia2V5IiA6ICJqc29uc2NoZW1hIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQiLCJ0YWciIDogImRlbW8ifSwKCQkgICAgeyJrZXkiIDogImF6dXJlIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQiLCJ0YWciIDogImRlbW8ifSwKIHsia2V5IiA6ICJvcGVuYXBpIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwczovL2l5bm8zbXp4MWguZXhlY3V0ZS1hcGkuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vRGV2ZWxvcG1lbnQifSwKCQkgICAgeyJrZXkiIDogImx3bTJtIiwgInBsdWdpblR5cGUiOiAiaW1wb3J0ZXIiLCAibmFtZSIgOiAiTHdNMk0iICwgImZpbGVUeXBlIiA6ICIueG1sIiwgImRlc2NyaXB0aW9uIiA6ICJDb252ZXJ0cyBMd00yTSBkZXNjcmlwdGlvbnMgdG8gVm9ydG8iLCAiZW5kcG9pbnQiIDogImh0dHBzOi8vaXlubzNtengxaC5leGVjdXRlLWFwaS5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS9EZXZlbG9wbWVudCJ9XQ=="

# Plugin Configuration for generators running locally
#plugins : "W3sia2V5IiA6ICJib3NjaGlvdHN1aXRlIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwOi8vbG9jYWxob3N0OjgwODEvZ2VuZXJhdG9ycyJ9LAoJCQl7ImtleSIgOiAiZWNsaXBzZWRpdHRvIiwgInBsdWdpblR5cGUiOiAiZ2VuZXJhdG9yIiwgImFwaVZlcnNpb24iIDogIjIiICwgImVuZHBvaW50IiA6ICJodHRwOi8vbG9jYWxob3N0OjgwODEvZ2VuZXJhdG9ycyJ9LAoJCSAgICB7ImtleSIgOiAiZWNsaXBzZWhvbm8iLCAicGx1Z2luVHlwZSI6ICJnZW5lcmF0b3IiLCAiYXBpVmVyc2lvbiIgOiAiMiIgLCAiZW5kcG9pbnQiIDogImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9nZW5lcmF0b3JzIn0sCiB7ImtleSIgOiAib3BlbmFwaSIsICJwbHVnaW5UeXBlIjogImdlbmVyYXRvciIsICJhcGlWZXJzaW9uIiA6ICIyIiAsICJlbmRwb2ludCIgOiAiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2dlbmVyYXRvcnMifV0="

server:
  port: 8443
  contextPath: /infomodelrepository
  use-forward-headers: true
  ssl:
    key-store: src/main/resources/selfsigned.jks
    key-store-password: bosch123!
    keyStoreType: jks
    keyAlias: tomcat
    
eidp:
  oauth2:
    enabled: false
    resource:
      logoutRedirectUrl: https://localhost:8443/infomodelrepository/logout
      
# To connect to a database, uncomment the section below and use the mysql config file for repo
#spring:
#  datasource:
#    testWhileIdle: true
#    timeBetweenEvictionRunsMillis: 60000
#    wait_timeout: 180
#    validationInterval: 60    
#    validationQuery: SELECT 1
#    driver-class-name:
#    url:
#    username:
#    password:
#  jpa:
#    show-sql: false
#    generate-ddl: true
#  hibernate:
#    ddl-auto: validate