baseurl = "https://www.eclipse.org/vorto/"
languageCode = "en-us"
title = "Eclipse Vorto"
theme = "hugo-material-docs"
metadataformat = "toml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "The Eclipse Vorto Project"
	description = "Describe. Share. Integrate."
	copyright = "The Eclipse Vorto Project"
	version = ""
  	logo = "images/vorto.png"
  	favicon = "images/vorto.ico"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/eclipse/vorto"
	
	hipp_url = "https://ci.eclipse.org/vorto"

	permalink = "#"

	# Custom assets
	custom_css = ["css/vorto.css","//www.eclipse.org/eclipse.org-common/themes/solstice/public/stylesheets/vendor/cookieconsent/cookieconsent.min.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "VortoIoT"
	github  = "eclipse/vorto"
	email   = "vorto-dev@eclipse.org"
	mailinglist = "https://accounts.eclipse.org/mailing-list/vorto-dev"


[[menu.main]]
	name   = "What is Vorto"
	url    = "introduction"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 20

[[menu.main]]
	name   = "Tutorials"
	url    = "tutorials/"
	weight = 30

[[menu.main]]
	name   = "Downloads"
	url    = "downloads/"
	weight = 40

[[menu.main]]
	name   = "Community"
	url    = "community/"
	weight = 50

[[menu.main]]
	name   = "Release Notes"
	url    = "release-notes/"
	weight = 60
	
[[menu.main]]
	name   = "Reference Documentation"
	url    = "documentation/"
	weight = 70

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true